### ISSUE TITLE
Tests not getting set up properly

### ISSUE THREAD

**Issue by hijonathan** [divshot/grunt-divshot#3]
Running `grunt test` complains that assets in the `tmp` dir don't exist, which is true.

```
github/grunt-divshot [promote] » grunt test
Running "clean:tests" (clean) task

Running "nodeunit:tests" (nodeunit) task
Testing divshot_test.jsFF
>> divshot - default_options
>> Error: Expected 1 assertions, 0 ran
>> at Object.oncomplete (fs.js:107:15)

>> divshot - default_options
>> Error: Unable to read "tmp/default_options" file (Error code: ENOENT).
>> at Object.util.error (node_modules/grunt/lib/grunt/util.js:56:39)
>> at Object.file.read (node_modules/grunt/lib/grunt/file.js:239:22)
>> at Object.exports.divshot.default_options (test/divshot_test.js:33:29)
>> at Object.exports.divshot.setUp (test/divshot_test.js:28:5)
>> at Object.oncomplete (fs.js:107:15)

>> divshot - custom_options
>> Error: Expected 1 assertions, 0 ran
>> at processImmediate [as _immediateCallback] (timers.js:330:15)

>> divshot - custom_options
>> Error: Unable to read "tmp/custom_options" file (Error code: ENOENT).
>> at Object.util.error (node_modules/grunt/lib/grunt/util.js:56:39)
>> at Object.file.read (node_modules/grunt/lib/grunt/file.js:239:22)
>> at Object.exports.divshot.custom_options (test/divshot_test.js:42:29)
>> at Object.exports.divshot.setUp (test/divshot_test.js:28:5)
>> at processImmediate [as _immediateCallback] (timers.js:330:15)

Warning: 4/4 assertions failed (23ms) Use --force to continue.

Aborted due to warnings.
```

**Comment by tayloryork** [comment]
Did you ever figure this out? I'm having the same issue.

**Comment by scottcorgan** [comment]
You found my secret. This module has no tests. In fact, I need to do a whole rewrite with tests. Coming in the next couple of weeks. Either of you up for making it happen?

**Comment by hijonathan** [comment]
@scottcorgan the rewrite or the tests?

**Comment by tayloryork** [comment]
I actually figured out what was going on here.
The grunt-init grunt-plugin that we use to start plugin comes with a standard task & standard gruntfile & standard tests.  
This is what happens when you run 'grunt test' on a brand new clean grunt-plugin:
1. The task take the configuration from the gruntfile, which contains a key value pair "file : 'tmp/default_options' " and creates that file.
2. The standard task It uses some of the configuration to determine what should go in that file.
3. The standard test is hard coded to look for tmp/default_options and compare it to a checked in file, /test/fixtures/default_options.

When you changed the task to not create the 'file' from the key, the test doesn't work anymore, but it is a real PITA to figure out when you have never made a grunt-plugin or a node.js app before and you assume there is some magic going on that you don't know about yet.

The solution for this project is to just rewrite (or delete) the standard test.

**Comment by scottcorgan** [comment]
@hijonathan both!

**Comment by scottcorgan** [comment]
@tayloryork yes, the initial tests scaffolded with grunt will not work with the current code. Moving forward, this will change. I apologize for the miscommunication in the readme

**Comment by hijonathan** [comment]
@scottcorgan sure, though I probably can't get to it until next weekend (March 14-16). Is that alright? Also, I can't promise to support the old config syntax, which I have not really been a fan of :skull:

I'm thinking something like this:

``` coffeescript
grunt.initConfig
  divshot: 
    options: # some options here for all divshot commands.
    push:
      options: # divshot:push:* overrides.
      staging:
        options: # divshot:push:staging overrides.
```

Will probably just support `push` and `promote` (#2) to start.

**Comment by scottcorgan** [comment]
@hijonathan  Which part were you not a fan of in the old syntax?

**Comment by hijonathan** [comment]
@scottcorgan just lots of repetition. Seems like it didn't inherit options properly, so I ended up with configs that looked like this:

``` coffeescript
grunt.initConfig
    'divshot:push:development':
        options:
            token: grunt.option('token')
            binPath: './node_modules/.bin'
    'divshot:push:staging':
        options:
            token: grunt.option('token')
            binPath: './node_modules/.bin'
    'divshot:push:production':
        options:
            token: grunt.option('token')
            binPath: './node_modules/.bin'
    'divshot:promote':
        options:
            token: grunt.option('token')
            binPath: './node_modules/.bin'
```

Could just be me doing it wrong, but I think I ran into issues using a nested inheritance.

**Comment by scottcorgan** [comment]
Seems you've taken the plugin a bit further than intended. You shouldn't have to add to stuff like `binPath` to the options.

Anyway, Feel free to submit what you want it to look like. But, since it's open source, please submit javascript instead of Coffeescript.

Once you submit the interface, we can move forward from there.

**Comment by hijonathan** [comment]
@scottcorgan `binPath` option was to unshackle this from a typical file structure. Useful when running this from a CI server, where output files are separated from utility scripts like Grunt.

Np on the js over coffee, though I think the "since it's open source" clause isn't a strong argument against coffee these days. Some of the most popular open source projects in the past several months are written in coffee. All of Github's new [Atom Editor](https://github.com/atom) is written in coffee. It's definitely here to stay :]

**Comment by hijonathan** [comment]
When you get a chance, can you add an [.editorconfig](http://editorconfig.org/) file? Would make it easy to follow your lead on coding style.

**Comment by scottcorgan** [comment]
You're welcome to add the .editorconfig file. Do it in whatever is easiest for you. Let me know when you have an api layout so we can review. Thanks again!

**Comment by scottcorgan** [comment]
Due to the changes in Divshot internally (both Superstatic, and our private settings), we've had to make some changes internally to this module. I'll close this PR and you can open a new one compatible with 0.4.0.

Thanks man!
